--- pyopenssl-24.2.1/tests/test_ssl.py.orig
+++ pyopenssl-24.2.1/tests/test_ssl.py
@@ -2387,6 +2387,7 @@
         clientSSL.connect((loopback_address(port), port.getsockname()[1]))
         # XXX An assertion?  Or something?
 
+    @pytest.mark.skip(reason="usually fails: https://github.com/pyca/pyopenssl/issues/1192")
     def test_connect_ex(self):
         """
         If there is a connection error, `Connection.connect_ex` returns the
