Fix for Python 3 and libVTE-2.9.1

--- github/gnome_connection_manager.py	2020-04-07 17:30:35.000000000 +0000
+++ fixed/gnome_connection_manager.py	2020-04-14 18:16:49.251016288 +0000
@@ -439,8 +439,13 @@
     return s
 
 def vte_feed(terminal, data):
-    if TERMINAL_V048:
-        terminal.feed_child(data.encode('utf-8'))
+    if TERMINAL_V048 or (Vte.MAJOR_VERSION, Vte.MINOR_VERSION) >= (0, 42):
+        try:
+            terminal.feed_child(data.encode('utf-8'))
+        except TypeError as e:
+            # https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1780501
+            # The doc does not say clearly at which version the feed_child* function has lost # the "len" parameter :(
+            terminal.feed_child(data, len(data))
     else:
         terminal.feed_child(data, len(data))
                 
